### ISSUE TITLE
issue validating arrays: AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by markfink** [Trax-air/swagger-parser#54]
in my opinion swagger-parser is `not handling arrays correctly` (see trace at the bottom). I tried with both python2.7 and python3.6. This relates to `validate_request` - `definitions_example` works fine.

I had to patch the code to make ist work properly (line 502):
```python
        # Check no extra arg & type
        if isinstance(dict_to_test, list):
            properties_dict = spec_def.get('items', {})
            for value in dict_to_test:
                if not self._validate_type(properties_dict, value):
                    return True
        else:
            properties_dict = spec_def.get('properties', {})
            for key, value in dict_to_test.items():
                if value is not None:
                    if key not in properties_dict:  # Extra arg
                        return False
                    else:  # Check type
                        if not self._validate_type(properties_dict[key], value):
                            return False
```

relevant part of my spec:
``` yaml
definitions:
  NotificationARNs:
    type: array
    items:
      type: string
      example: arn:aws:sns:eu-west-1:123456789012:mytopic1
```

``` text
Traceback (most recent call last):
  File "config_validate_kumo.py", line 37, in <module>
    parser.validate_request('/kumo', 'get', body=my_config)
  File "/Users/fin0007m/devel/gcdt/bvenv/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 713, in validate_request
    is_ok, msg = self._validate_body_parameters(body, action_spec)
  File "/Users/fin0007m/devel/gcdt/bvenv/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 793, in _validate_body_parameters
    if not self.validate_definition(definition_name, body):
  File "/Users/fin0007m/devel/gcdt/bvenv/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 508, in validate_definition
    if not self._validate_type(properties_dict[key], value):
  File "/Users/fin0007m/devel/gcdt/bvenv/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 526, in _validate_type
    return self.validate_definition(def_name, value)
  File "/Users/fin0007m/devel/gcdt/bvenv/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 508, in validate_definition
    if not self._validate_type(properties_dict[key], value):
  File "/Users/fin0007m/devel/gcdt/bvenv/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 526, in _validate_type
    return self.validate_definition(def_name, value)
  File "/Users/fin0007m/devel/gcdt/bvenv/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 503, in validate_definition
    for key, value in dict_to_test.items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by cyprieng** [comment]
Thank you for reporting this issue ! I will try to fix this soon
